//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlMajd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyValues
    {
        public int CurrencyValueId { get; set; }
        public Nullable<decimal> dollarVlaue { get; set; }
        public Nullable<decimal> JDValue { get; set; }
        public Nullable<decimal> euroValue { get; set; }
        public Nullable<decimal> NISValue { get; set; }
    }
}
