//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlMajd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotaleMoney
    {
        public int totaleId { get; set; }
        public Nullable<decimal> totaleDollar { get; set; }
        public Nullable<decimal> totaleJD { get; set; }
        public Nullable<decimal> totaleEuro { get; set; }
        public Nullable<decimal> totaleNIS { get; set; }
        public Nullable<System.DateTime> dateOfTotale { get; set; }
    }
}
